### ISSUE TITLE
Large number of files generated

### ISSUE THREAD

**Issue by saberraz** [MerginMaps/media-sync#22]
media_sync is creating files (probably log files) which caused the maximum capacity of Inodes to be overloaded  on the server (from 0 to +6.5 million in 4 weeks !).

**Comment by wonder-sk** [comment]
This is the likely cause: https://github.com/MerginMaps/mergin-py-client/issues/47

**Comment by saberraz** [comment]
It does not appear to be the case. There are still several files generated as the result of media-sync

**Comment by wonder-sk** [comment]
Python client needs updating in media-sync
