### ISSUE TITLE
Error when skipping URL update

### ISSUE THREAD

**Issue by saberraz** [MerginMaps/media-sync#26]
When I skip URL updates by removing the references section from the config file, i.e. lines 26-30 in 
`https://github.com/MerginMaps/mergin-media-sync/blob/main/config.yaml.default`

I get the following error:
`Silent ignoring references section if not contained in config file.`
​

**Comment by rastermanden** [comment]
This is not correct.

We would like the service to not throw an error if the "references" section is missing form config.yaml.

At the moment it works and copies/moves files but throws an error if the references section is not present. It would be nice not to have this error in logfiles

**Comment by rastermanden** [comment]
This is related to #20 

We want to entirely skip updating references in a table and just copy to a bucket

```bash
docker stop mergin-media-sync
docker rm  mergin-media-sync
docker run -it \
  -v /tmp/mediasync:/data \
  --name mergin-media-sync \
  -e MERGIN__USERNAME=admin \
  -e MERGIN__URL=https://myrurl\
  -e MERGIN__PASSWORD=septima4you \
  -e MERGIN__PROJECT_NAME=myuser/media-syn-test \
  -e LOCAL__DEST=/data \
  -e OPERATION_MODE=copy \
  -e DRIVER=minio \
  -e MINIO__ENDPOINT="s3.dualstack.eu-central-1.amazonaws.com" \
  -e MINIO__REGION=eu-central-1 \
  -e MINIO__ACCESS_KEY=XXXXX \
  -e MINIO__SECRET_KEY=XXXXX \
  -e MINIO__BUCKET=mergin-sync-test \
  -e MINIO__SECURE=1 \
  -e MINIO__BUCKET_SUBPATH=newtest \
  lutraconsulting/mergin-media-sync python3 media_sync_daemon.py
```

Fails with 
```
Updating references ...
Error: SQLITE error: no such table: notes
```

**Comment by rastermanden** [comment]
It seems that with new version 0.4.0 you still have to add (e REFERENCES="[]" \) a reference section with an empty array. Otherwise it uses a defult confif with a "notes" table.
```
Error: SQLITE error: no such table: notes
```

**Comment by JanCaha** [comment]
I can quite see how this would happen, unless the specification is somewhere in the `config.yaml`.  There are explicit checks that replace setup `references` as `[]` if the `references` are missing from the config file or if it does not have value at all. The default yaml file is not read anywhere in the media sync.
